In [ ]:
Create a list and add one more element at the end of the list

In [57]:
a=[10,20,30]
print (a)

[10, 20, 30]


In [58]:
a.append(40)
print (a)

[10, 20, 30, 40]


In [ ]:
Create a function to calculate product of two numbers

In [ ]:
def calculate_product(a,b):
    return a*b

In [ ]:
Num1 = 5
Num2 = 8
product = calculate_product(Num1, Num2)
print(f"The product of {Num1} and {Num2} is {product}.")

In [ ]:
Create a parametric function to convert celsius to fahrenheit

In [ ]:
Num1 = 6
Num2 = 7
product = calculate_product(Num1, Num2)
print(f"The product of {Num1} and {Num2} is {product}.")

In [24]:
def fahrenheit(T):
    return((9/5)*(T+32))
f=fahrenheit(35)
f

120.60000000000001

In [27]:
def celcius(T):
   return((5/9)*(T+32))
c=celcius(100)
c

73.33333333333334

In [ ]:
create two numpy arrays and perform broadcasting.

In [28]:
import numpy as np

In [29]:
array1 = np.array([1,2,3,4])
array2 = np.array([10,20,30,40])

In [31]:
result = array1 + array2
print("Broadcasted Result:\n",result)

Broadcasted Result:
 [11 22 33 44]


In [33]:
array1 = np.array([5,6,7,8])
array2 = np.array([10,20,30,40])

In [34]:
result = array1 + array2
print("Broadcasted Result:\n",result)

Broadcasted Result:
 [15 26 37 48]


In [ ]:
create a numpy array and convert it into a dataframe

In [44]:
arr=np.array([1,2,3],dtype=np.float32)
arr

array([1., 2., 3.], dtype=float32)

In [45]:
b=np.array([10,20,30,40],dtype=np.int64)
b

array([10, 20, 30, 40], dtype=int64)

In [ ]:
create a Dictionary and convert it into a DataFrame

In [46]:
import pandas as pd

In [47]:
Data = {"Name": ["Alice","Bob"], "Age": [25,22]}

In [48]:
df_dict = pd.DataFrame(Data)
print(df_dict)

    Name  Age
0  Alice   25
1    Bob   22


In [51]:
Data=[['Brindha',23],['Abi',25],['Azar',26]]
df=pd.DataFrame(Data)
df

0   1
0  Brindha  23
1      Abi  25
2     Azar  26

In [54]:
df=pd.DataFrame(Data,columns=['Name','Age'])
df

Name  Age
0  Brindha   23
1      Abi   25
2     Azar   26